#!/bin/bash

CDN_TXT=$(curl -s "$CDN_URL")
# Ensure CDN_TXT is not empty
if [[ -z "$CDN_TXT" ]]; then
    echo "Error: CDN_TXT variable is empty. Exiting."
    exit 1
fi

PACKAGE_URL=$(echo "$CDN_TXT" | grep -oP '(?<=https://)[^\s]*')
PACKAGE_VERSION=$(echo "$PACKAGE_URL" | grep -oP 'steamlink-rpi-bookworm-arm64-([0-9]+\.[0-9]+\.[0-9]+(?:\.[0-9]+)?)' | cut -d'-' -f4)

version_check() {
    if [[ -f "$GAMEDIR/bin/version_${DEVICE_ARCH}.txt" ]]; then
        CURRENT_VERSION=$(grep -oP 'steamlink-rpi-bookworm-arm64-([0-9]+\.[0-9]+\.[0-9]+(?:\.[0-9]+)?)' "$GAMEDIR/bin/version_${DEVICE_ARCH}.txt" | cut -d'-' -f4)
        
        if [[ "$CURRENT_VERSION" == "$PACKAGE_VERSION" ]]; then
            echo "Version is up to date. No need to download."
            return 1
        else
            echo "Version has changed. Downloading new package."
            return 0
        fi
    else
        echo "No version.txt found. Downloading new package."
        return 0
    fi
}

download_steamlink() {
    if version_check; then
        PACKAGE_URL="https://$PACKAGE_URL"
        
        mkdir -p "$GAMEDIR/bin"
        echo "$PACKAGE_URL" > "$GAMEDIR/bin/version_${DEVICE_ARCH}.txt"
        
        echo "Downloading package from: $PACKAGE_URL"
        
        wget "$PACKAGE_URL" -O steamlink-package.tar.gz || { echo "Error: Download failed."; exit 1; }
        
        echo "Download complete!"
        
        echo "Searching for 'shell' binary in the archive..."
        SHELL_PATH=$(tar -tzf steamlink-package.tar.gz | grep -i '/shell$')

        if [[ -n "$SHELL_PATH" ]]; then
            echo "Extracting $SHELL_PATH from steamlink-package.tar.gz..."
            tar -xvzf steamlink-package.tar.gz "$SHELL_PATH" -O > "$GAMEDIR/bin/shell.${DEVICE_ARCH}"
            chmod +x "$GAMEDIR/bin/shell.${DEVICE_ARCH}"
            
            echo "Searching for 'lib' folder in the archive..."
            LIB_PATH=$(tar -tzf steamlink-package.tar.gz | grep -m1 -oE '^[^/]+/lib/')

            if [[ -n "$LIB_PATH" ]]; then
                echo "Extracting needed libraries from package."
                mkdir -p "$GAMEDIR/libs.${DEVICE_ARCH}"
                tar -xvzf steamlink-package.tar.gz -C "$GAMEDIR/libs.${DEVICE_ARCH}" --strip-components=2 $(tar -tzf steamlink-package.tar.gz | grep "^${LIB_PATH}")
                
                echo "Searching for 'Qt-x.xx.x' folder in the archive..."
                QT_PATH=$(tar -tzf steamlink-package.tar.gz | grep -oE '^[^/]+/Qt-[0-9]+\.[0-9]+\.[0-9]+/' | head -n1)

                if [[ -n "$QT_PATH" ]]; then
                    echo "Extracting $QT_PATH folder..."
                    tar -xvzf steamlink-package.tar.gz -C "$GAMEDIR/" --strip-components=1 $(tar -tzf steamlink-package.tar.gz | grep "^${QT_PATH}")
                    rm -rf steamlink-package.tar.gz
                else
                    echo "Qt not found in the archive!"
                fi
            else
                echo "Could not find libraries!"
                exit 1
            fi
        else
            echo "Could not find shell binary in the archive!"
            exit 1
        fi
    fi
}

download_steamlink
